"""empty message

Revision ID: 765531343d2a
Revises: a19163f60f72
Create Date: 2018-08-17 22:33:41.376960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '765531343d2a'
down_revision = 'a19163f60f72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('department', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('remarks', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'remarks')
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'location')
    op.drop_column('users', 'last_seen')
    op.drop_column('users', 'department')
    # ### end Alembic commands ###
