"""empty message

Revision ID: 80c0aedde0c7
Revises: 2f2182e74ca9
Create Date: 2018-08-28 22:44:38.066269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c0aedde0c7'
down_revision = '2f2182e74ca9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reserve_infos', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reserve_infos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reserve_infos', type_='foreignkey')
    op.drop_column('reserve_infos', 'user_id')
    # ### end Alembic commands ###
